spring:
  h2:
    console:
      enabled: false


  jpa:
    show-sql: true
    defer-datasource-initialization: true
spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5

  ## PostgreSQL
spring.datasoource.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: Tagore@007

  #drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto: update
